// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookupApi.Models;

#nullable disable

namespace ParksLookupApi.Migrations
{
    [DbContext(typeof(ParksLookupApiContext))]
    [Migration("20230331180649_State")]
    partial class State
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookupApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkName = "Olympic National Park",
                            State = "WA",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkName = "North Cascades National Park",
                            State = "WA",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkName = "Tiger Mountain State Forest",
                            State = "WA",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkName = "Mike Roess Gold Head Branch State Park",
                            State = "FL",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkName = "Everglades National Park",
                            State = "FL",
                            Type = "National"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
